name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          scheme: OpenAIBar
        run: |
          xcodebuild
      - name: Tar built app
        run: |
          tar -cvzf openaibar.app.tgz -C build/Release OpenAIBar.app
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenAIBar.app.tgz
          path: openaibar.app.tgz
